//! File Integrity Monitoring types.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Type of file change detected by FIM.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FimChangeType {
    /// A new file was created.
    Created,
    /// An existing file was modified (content change).
    Modified,
    /// A file was deleted.
    Deleted,
    /// File permissions were changed.
    PermissionChanged,
    /// A file was renamed or moved.
    Renamed,
}

impl FimChangeType {
    /// Human-readable label for the change type.
    pub fn label(&self) -> &'static str {
        match self {
            FimChangeType::Created => "Created",
            FimChangeType::Modified => "Modified",
            FimChangeType::Deleted => "Deleted",
            FimChangeType::PermissionChanged => "Permission Changed",
            FimChangeType::Renamed => "Renamed",
        }
    }
}

/// Alert generated by the FIM engine when a file change is detected.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FimAlert {
    /// Path of the affected file.
    pub path: PathBuf,

    /// Type of change detected.
    pub change: FimChangeType,

    /// Hash of the file before the change (None for new files).
    pub old_hash: Option<String>,

    /// Hash of the file after the change (None for deleted files).
    pub new_hash: Option<String>,

    /// Size of the file after the change (None for deleted files).
    pub new_size: Option<u64>,

    /// When the change was detected.
    pub timestamp: DateTime<Utc>,

    /// Whether this alert has been acknowledged by the user.
    #[serde(default)]
    pub acknowledged: bool,
}

/// Baseline entry for a monitored file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FimBaseline {
    /// Path of the monitored file.
    pub path: PathBuf,

    /// BLAKE3 hash of file contents.
    pub hash: String,

    /// File permissions (Unix mode bits, 0 on Windows).
    pub permissions: u32,

    /// File size in bytes.
    pub size: u64,

    /// Last modification time of the file.
    pub modified_at: DateTime<Utc>,

    /// When the baseline was captured.
    pub captured_at: DateTime<Utc>,
}

/// Configuration for FIM watched paths.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FimPolicy {
    /// Paths to monitor for changes.
    pub watched_paths: Vec<PathBuf>,

    /// Glob patterns to exclude from monitoring.
    #[serde(default)]
    pub ignore_patterns: Vec<String>,

    /// Whether to use recursive watching.
    #[serde(default = "default_true")]
    pub recursive: bool,

    /// Debounce interval in milliseconds for file events.
    #[serde(default = "default_debounce_ms")]
    pub debounce_ms: u64,
}

fn default_true() -> bool {
    true
}

fn default_debounce_ms() -> u64 {
    500
}

impl Default for FimPolicy {
    fn default() -> Self {
        Self {
            watched_paths: Self::default_watched_paths(),
            ignore_patterns: vec![
                "*.log".to_string(),
                "*.tmp".to_string(),
                "*.swp".to_string(),
                ".git/**".to_string(),
            ],
            recursive: true,
            debounce_ms: 500,
        }
    }
}

impl FimPolicy {
    /// Default monitored paths per platform.
    pub fn default_watched_paths() -> Vec<PathBuf> {
        #[cfg(target_os = "windows")]
        {
            vec![
                PathBuf::from(r"C:\Windows\System32\drivers\etc"),
                PathBuf::from(r"C:\Windows\System32\config"),
            ]
        }
        #[cfg(target_os = "macos")]
        {
            vec![
                PathBuf::from("/etc"),
                PathBuf::from("/Library/LaunchDaemons"),
                PathBuf::from("/Library/LaunchAgents"),
            ]
        }
        #[cfg(target_os = "linux")]
        {
            vec![
                PathBuf::from("/etc"),
                PathBuf::from("/usr/bin"),
                PathBuf::from("/usr/sbin"),
            ]
        }
        #[cfg(not(any(target_os = "windows", target_os = "macos", target_os = "linux")))]
        {
            vec![PathBuf::from("/etc")]
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fim_change_type_label() {
        assert_eq!(FimChangeType::Created.label(), "Created");
        assert_eq!(FimChangeType::Deleted.label(), "Deleted");
    }

    #[test]
    fn test_fim_alert_serialization() {
        let alert = FimAlert {
            path: PathBuf::from("/etc/passwd"),
            change: FimChangeType::Modified,
            old_hash: Some("abc123".to_string()),
            new_hash: Some("def456".to_string()),
            new_size: Some(1024),
            timestamp: Utc::now(),
            acknowledged: false,
        };

        let json = serde_json::to_string(&alert).unwrap();
        let parsed: FimAlert = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.change, FimChangeType::Modified);
        assert_eq!(parsed.path, PathBuf::from("/etc/passwd"));
    }

    #[test]
    fn test_fim_policy_default() {
        let policy = FimPolicy::default();
        assert!(policy.recursive);
        assert_eq!(policy.debounce_ms, 500);
        assert!(!policy.watched_paths.is_empty());
    }

    #[test]
    fn test_fim_baseline_serialization() {
        let baseline = FimBaseline {
            path: PathBuf::from("/etc/hosts"),
            hash: "abc123def456".to_string(),
            permissions: 0o644,
            size: 512,
            modified_at: Utc::now(),
            captured_at: Utc::now(),
        };

        let json = serde_json::to_string(&baseline).unwrap();
        let parsed: FimBaseline = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.hash, "abc123def456");
    }
}
