// Copyright (c) 2024-2026 Cyber Threat Consulting
// SPDX-License-Identifier: MIT

//! File Integrity Monitoring types.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Type of file change detected by FIM.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FimChangeType {
    /// A new file was created.
    Created,
    /// An existing file was modified (content change).
    Modified,
    /// A file was deleted.
    Deleted,
    /// File permissions were changed.
    PermissionChanged,
    /// A file was renamed or moved.
    Renamed,
}

impl std::fmt::Display for FimChangeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Created => write!(f, "created"),
            Self::Modified => write!(f, "modified"),
            Self::Deleted => write!(f, "deleted"),
            Self::PermissionChanged => write!(f, "permission_changed"),
            Self::Renamed => write!(f, "renamed"),
        }
    }
}

impl FimChangeType {
    /// Human-readable label for the change type.
    pub fn label(&self) -> &'static str {
        match self {
            FimChangeType::Created => "Created",
            FimChangeType::Modified => "Modified",
            FimChangeType::Deleted => "Deleted",
            FimChangeType::PermissionChanged => "Permission Changed",
            FimChangeType::Renamed => "Renamed",
        }
    }
}

/// Alert generated by the FIM engine when a file change is detected.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FimAlert {
    /// Path of the affected file.
    pub path: PathBuf,

    /// Type of change detected.
    pub change: FimChangeType,

    /// Hash of the file before the change (None for new files).
    pub old_hash: Option<String>,

    /// Hash of the file after the change (None for deleted files).
    pub new_hash: Option<String>,

    /// Size of the file after the change (None for deleted files).
    pub new_size: Option<u64>,

    /// When the change was detected.
    pub timestamp: DateTime<Utc>,

    /// Whether this alert has been acknowledged by the user.
    #[serde(default)]
    pub acknowledged: bool,
}

/// Baseline entry for a monitored file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FimBaseline {
    /// Path of the monitored file.
    pub path: PathBuf,

    /// BLAKE3 hash of file contents.
    pub hash: String,

    /// File permissions (Unix mode bits, 0 on Windows).
    pub permissions: u32,

    /// File size in bytes.
    pub size: u64,

    /// Last modification time of the file.
    pub modified_at: DateTime<Utc>,

    /// When the baseline was captured.
    pub captured_at: DateTime<Utc>,
}

/// Configuration for FIM watched paths.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FimPolicy {
    /// Paths to monitor for changes.
    pub watched_paths: Vec<PathBuf>,

    /// Patterns to exclude from monitoring, matched case-insensitively:
    /// `*suffix` (path ends with `suffix`), `dir/**` (inside a directory named
    /// `dir`) or `name` (a file or directory named `name`, and its content).
    /// `dir` and `name` are whole path components, not substrings.
    #[serde(default)]
    pub ignore_patterns: Vec<String>,

    /// Whether to use recursive watching.
    #[serde(default = "default_true")]
    pub recursive: bool,

    /// Debounce interval in milliseconds for file events.
    #[serde(default = "default_debounce_ms")]
    pub debounce_ms: u64,
}

fn default_true() -> bool {
    true
}

fn default_debounce_ms() -> u64 {
    500
}

/// Ignore patterns that protect the agent from watching its own files.
///
/// Kept separate from the other defaults because these are an invariant, not a
/// preference: [`FimPolicy::with_self_exclusions`] re-applies them to every
/// policy, including ones pushed by the platform. Without that, a server config
/// omitting `ignore_patterns` (the field defaults to empty) combined with a
/// watched path covering the agent's data directory produces a self-sustaining
/// loop -- FIM alerts on `agent.db` writes, which are themselves written to
/// `agent.db`.
///
/// Every entry names a directory (or a log file) the agent itself writes to on
/// one of the supported platforms. Entries are matched case-insensitively
/// against whole path components: `sentinel/**` covers
/// `/etc/sentinel/agent.json` but neither `/etc/sentinel-update` nor a file
/// called `sentinel`. Anything broader is a way to evade monitoring by naming
/// a file after the agent, so a directory the agent starts writing to must be
/// listed here by its exact name.
pub const SELF_EXCLUSION_PATTERNS: &[&str] = &[
    // Linux: /etc/sentinel (config), /var/log/sentinel and
    // ~/.local/share/sentinel (logs). Windows: %ProgramData%\Sentinel and
    // %LOCALAPPDATA%\Sentinel (config, data, logs).
    "sentinel/**",
    // Linux: /var/lib/sentinel-grc (data), /var/log/sentinel-grc (logs),
    // /opt/sentinel-grc (install). Every platform: the quarantine store,
    // <local data dir>/sentinel-grc/quarantine.
    "sentinel-grc/**",
    // macOS: ~/Library/Application Support/SentinelGRC (config, data, logs).
    "SentinelGRC/**",
    "SentinelAgent.app/**",
    // Log directories used when the system-wide one is not writable: the
    // macOS per-user one, and the last-resort one under the temp directory.
    "com.sentinel-grc.Sentinel/**",
    "sentinel-logs/**",
    // GUI preferences (Linux and Windows, then macOS).
    "SentinelAgent/**",
    "com.CyberThreatConsulting.SentinelAgent/**",
    // macOS: launchd redirects the agent's and its helper's output, which
    // carries every log line, to these files.
    "var/log/sentinel-agent.log",
    "var/log/sentinel-agent.err",
    "var/log/sentinel-agent-helper.log",
];

impl FimPolicy {
    /// Return this policy with the agent's self-exclusion patterns guaranteed
    /// present, preserving any caller- or server-supplied patterns.
    #[must_use]
    pub fn with_self_exclusions(mut self) -> Self {
        for pattern in SELF_EXCLUSION_PATTERNS {
            if !self.ignore_patterns.iter().any(|p| p == pattern) {
                self.ignore_patterns.push((*pattern).to_string());
            }
        }
        self
    }
}

impl Default for FimPolicy {
    fn default() -> Self {
        Self {
            watched_paths: Self::default_watched_paths(),
            ignore_patterns: vec![
                "*.log".to_string(),
                "*.tmp".to_string(),
                "*.swp".to_string(),
                ".git/**".to_string(),
                // Windows: exclude transient user-profile caches under the config directory.
                // These generate hundreds of events (D3DSCache, Office telemetry, Xbox, etc.)
                // and are not security-relevant.
                "systemprofile/AppData/**".to_string(),
            ],
            recursive: true,
            debounce_ms: 500,
        }
        .with_self_exclusions()
    }
}

impl FimPolicy {
    /// Default monitored paths per platform.
    pub fn default_watched_paths() -> Vec<PathBuf> {
        #[cfg(target_os = "windows")]
        {
            let mut paths = vec![
                // hosts file — readable by all users
                PathBuf::from(r"C:\Windows\System32\drivers\etc"),
            ];
            // Registry hive directory — requires SYSTEM/admin privileges.
            // Only include if the path is accessible (avoids noisy errors
            // when running as a normal user or non-elevated service).
            let config_path = PathBuf::from(r"C:\Windows\System32\config");
            if std::fs::read_dir(&config_path).is_ok() {
                paths.push(config_path);
            }
            paths
        }
        #[cfg(target_os = "macos")]
        {
            vec![
                PathBuf::from("/etc"),
                PathBuf::from("/Library/LaunchDaemons"),
                PathBuf::from("/Library/LaunchAgents"),
            ]
        }
        #[cfg(target_os = "linux")]
        {
            vec![
                PathBuf::from("/etc"),
                PathBuf::from("/usr/bin"),
                PathBuf::from("/usr/sbin"),
            ]
        }
        #[cfg(not(any(target_os = "windows", target_os = "macos", target_os = "linux")))]
        {
            vec![PathBuf::from("/etc")]
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `ignore_patterns` is `#[serde(default)]`, so a server payload that omits
    /// the field deserializes to an empty vec. Re-applying the self-exclusions
    /// is what stops that from silently putting the agent's own database and
    /// config under watch.
    #[test]
    fn self_exclusions_survive_a_server_config_that_omits_them() {
        let from_server: FimPolicy =
            serde_json::from_str(r#"{"watched_paths":["/Library/Application Support"]}"#)
                .expect("deserialize server policy");
        assert!(
            from_server.ignore_patterns.is_empty(),
            "precondition: an omitted field yields no patterns"
        );

        let hardened = from_server.with_self_exclusions();
        for pattern in SELF_EXCLUSION_PATTERNS {
            assert!(
                hardened.ignore_patterns.iter().any(|p| p == pattern),
                "self-exclusion '{}' must be re-applied",
                pattern
            );
        }
    }

    #[test]
    fn self_exclusions_preserve_server_supplied_patterns_and_do_not_duplicate() {
        let policy = FimPolicy {
            watched_paths: vec![],
            ignore_patterns: vec!["custom/**".to_string(), "sentinel/**".to_string()],
            recursive: true,
            debounce_ms: 500,
        }
        .with_self_exclusions();

        assert!(
            policy.ignore_patterns.iter().any(|p| p == "custom/**"),
            "caller patterns must be preserved"
        );
        assert_eq!(
            policy
                .ignore_patterns
                .iter()
                .filter(|p| *p == "sentinel/**")
                .count(),
            1,
            "an already-present pattern must not be duplicated"
        );
    }

    #[test]
    fn default_policy_carries_self_exclusions() {
        let policy = FimPolicy::default();
        for pattern in SELF_EXCLUSION_PATTERNS {
            assert!(
                policy.ignore_patterns.iter().any(|p| p == pattern),
                "default policy is missing '{}'",
                pattern
            );
        }
    }

    #[test]
    fn test_fim_change_type_label() {
        assert_eq!(FimChangeType::Created.label(), "Created");
        assert_eq!(FimChangeType::Deleted.label(), "Deleted");
    }

    #[test]
    fn test_fim_alert_serialization() {
        let alert = FimAlert {
            path: PathBuf::from("/etc/passwd"),
            change: FimChangeType::Modified,
            old_hash: Some("abc123".to_string()),
            new_hash: Some("def456".to_string()),
            new_size: Some(1024),
            timestamp: Utc::now(),
            acknowledged: false,
        };

        let json = serde_json::to_string(&alert).unwrap();
        let parsed: FimAlert = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.change, FimChangeType::Modified);
        assert_eq!(parsed.path, PathBuf::from("/etc/passwd"));
    }

    #[test]
    fn test_fim_policy_default() {
        let policy = FimPolicy::default();
        assert!(policy.recursive);
        assert_eq!(policy.debounce_ms, 500);
        assert!(!policy.watched_paths.is_empty());
    }

    #[test]
    fn test_fim_baseline_serialization() {
        let baseline = FimBaseline {
            path: PathBuf::from("/etc/hosts"),
            hash: "abc123def456".to_string(),
            permissions: 0o644,
            size: 512,
            modified_at: Utc::now(),
            captured_at: Utc::now(),
        };

        let json = serde_json::to_string(&baseline).unwrap();
        let parsed: FimBaseline = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.hash, "abc123def456");
    }
}
