// Auto-generated by scripts/generate-version.js
// Default values committed to repo; overwritten at build time with actual timestamp.
export const BUILD_VERSION = '0.0.0-dev';
export const BUILD_TIMESTAMP = '1970-01-01T00:00:00.000Z';
