import { z } from 'zod';

export const assessmentAnswerSchema = z.object({
 value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]),
 comment: z.string().optional(),
 evidenceUrl: z.string().optional()
});

export const assessmentSchema = z.object({
 id: z.string().optional(), // Generated by backend/firebase
 templateId: z.string().min(1, "Le modèle est requis"),
 supplierId: z.string().min(1, "Le fournisseur est requis"),
 supplierName: z.string().min(1, "Le nom du fournisseur est requis"),
 status: z.enum(['Draft', 'Sent', 'In Progress', 'Submitted', 'Reviewed', 'Archived']),
 answers: z.record(z.string(), assessmentAnswerSchema).default({}),
 overallScore: z.number().min(0).max(100).default(0),
 riskLevel: z.enum(['Low', 'Medium', 'High', 'Critical']).optional(),
 respondentEmail: z.string().email().optional(),
 dueDate: z.string().optional()
});

export type AssessmentFormData = z.infer<typeof assessmentSchema>;
