import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const versionInfo = {
    version: new Date().getTime().toString(),
    timestamp: new Date().toISOString(),
};

const publicDir = path.join(__dirname, '../public');
const distDir = path.join(__dirname, '../dist');

// Ensure public directory exists
if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
}

// Write to public/version.json (for dev)
fs.writeFileSync(
    path.join(publicDir, 'version.json'),
    JSON.stringify(versionInfo, null, 2)
);

console.log('Generated public/version.json:', versionInfo);

// If dist exists (post-build), write there too just in case
if (fs.existsSync(distDir)) {
    fs.writeFileSync(
        path.join(distDir, 'version.json'),
        JSON.stringify(versionInfo, null, 2)
    );
    console.log('Generated dist/version.json');
}

// Write to src/config/version.ts for app to import
const configDir = path.join(__dirname, '../src/config');
if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
}

const versionTsContent = `// Auto-generated by scripts/generate-version.js
export const BUILD_VERSION = '${versionInfo.version}';
export const BUILD_TIMESTAMP = '${versionInfo.timestamp}';
`;

fs.writeFileSync(
    path.join(configDir, 'version.ts'),
    versionTsContent
);
console.log('Generated src/config/version.ts');
