// Copyright (c) 2024-2026 Cyber Threat Consulting
// SPDX-License-Identifier: MIT

//! Log correlation and analysis engine for SIEM integration.
//!
//! Provides rule-based pattern matching, event grouping, deduplication,
//! and threshold-based alerting on collected log events.

use crate::{EventCategory, SiemEvent};
use chrono::{DateTime, Duration, Utc};
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use tokio::sync::RwLock;
use tracing::{debug, info};

/// A correlation rule that matches events and may trigger alerts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrelationRule {
    /// Unique rule identifier.
    pub id: String,
    /// Human-readable name.
    pub name: String,
    /// Description of what this rule detects.
    pub description: String,
    /// Event categories this rule applies to (empty = all).
    pub categories: Vec<EventCategory>,
    /// Regex pattern to match against event descriptions.
    pub pattern: String,
    /// Minimum severity for events to match (0-10).
    pub min_severity: u8,
    /// Number of matching events within `window_secs` to trigger an alert.
    pub threshold: u32,
    /// Time window in seconds for threshold counting.
    pub window_secs: u64,
    /// Severity assigned to the generated alert.
    pub alert_severity: u8,
    /// Whether this rule is enabled.
    pub enabled: bool,
}

/// A compiled correlation rule ready for matching.
struct CompiledRule {
    rule: CorrelationRule,
    compiled_pattern: Regex,
}

/// Alert generated by correlation rules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrelationAlert {
    /// Rule that triggered this alert.
    pub rule_id: String,
    /// Rule name.
    pub rule_name: String,
    /// Alert description.
    pub description: String,
    /// Alert severity.
    pub severity: u8,
    /// Number of correlated events.
    pub event_count: u32,
    /// Time of the first correlated event.
    pub first_event: DateTime<Utc>,
    /// Time of the last correlated event.
    pub last_event: DateTime<Utc>,
    /// Sample event IDs that triggered this alert.
    pub sample_event_ids: Vec<String>,
    /// When the alert was generated.
    pub generated_at: DateTime<Utc>,
}

/// Tracks occurrences of events matching a rule within a time window.
struct RuleState {
    /// Timestamps of matching events.
    occurrences: Vec<DateTime<Utc>>,
    /// Sample event IDs.
    sample_ids: Vec<String>,
    /// Last time an alert was generated for this rule.
    last_alert: Option<DateTime<Utc>>,
}

impl RuleState {
    fn new() -> Self {
        Self {
            occurrences: Vec::new(),
            sample_ids: Vec::new(),
            last_alert: None,
        }
    }

    /// Add an occurrence and clean up expired entries.
    fn add_occurrence(&mut self, timestamp: DateTime<Utc>, event_id: &str, window: Duration) {
        let cutoff = Utc::now() - window;
        self.occurrences.retain(|t| *t > cutoff);
        self.occurrences.push(timestamp);

        if self.sample_ids.len() < 10 {
            self.sample_ids.push(event_id.to_string());
        }
    }

    /// Count occurrences within the window.
    fn count(&self, window: Duration) -> u32 {
        let cutoff = Utc::now() - window;
        self.occurrences.iter().filter(|t| **t > cutoff).count() as u32
    }
}

/// The correlation engine processes events against rules.
pub struct CorrelationEngine {
    rules: Vec<CompiledRule>,
    state: RwLock<HashMap<String, RuleState>>,
    alerts: RwLock<Vec<CorrelationAlert>>,
}

impl CorrelationEngine {
    /// Create a new correlation engine with the given rules.
    pub fn new(rules: Vec<CorrelationRule>) -> Self {
        let compiled: Vec<CompiledRule> = rules
            .into_iter()
            .filter(|r| r.enabled)
            .filter_map(|r| {
                match Regex::new(&r.pattern) {
                    Ok(compiled_pattern) => Some(CompiledRule {
                        rule: r,
                        compiled_pattern,
                    }),
                    Err(e) => {
                        tracing::warn!("Invalid regex in rule '{}': {}", r.id, e);
                        None
                    }
                }
            })
            .collect();

        info!("Correlation engine initialized with {} rules", compiled.len());

        Self {
            rules: compiled,
            state: RwLock::new(HashMap::new()),
            alerts: RwLock::new(Vec::new()),
        }
    }

    /// Create a correlation engine with built-in default rules.
    pub fn with_default_rules() -> Self {
        Self::new(default_rules())
    }

    /// Process a single event against all rules.
    ///
    /// Returns any alerts triggered by this event.
    pub async fn process_event(&self, event: &SiemEvent) -> Vec<CorrelationAlert> {
        let mut triggered = Vec::new();

        for compiled in &self.rules {
            if !self.event_matches(event, compiled) {
                continue;
            }

            let window = Duration::seconds(compiled.rule.window_secs as i64);
            let mut state = self.state.write().await;
            let rule_state = state
                .entry(compiled.rule.id.clone())
                .or_insert_with(RuleState::new);

            rule_state.add_occurrence(event.timestamp, &event.event_id, window);

            let count = rule_state.count(window);
            if count >= compiled.rule.threshold {
                // Avoid duplicate alerts within the same window
                let should_alert = rule_state
                    .last_alert
                    .map(|last| Utc::now() - last > window)
                    .unwrap_or(true);

                if should_alert {
                    let alert = CorrelationAlert {
                        rule_id: compiled.rule.id.clone(),
                        rule_name: compiled.rule.name.clone(),
                        description: format!(
                            "{}: {} events in {} seconds",
                            compiled.rule.description, count, compiled.rule.window_secs
                        ),
                        severity: compiled.rule.alert_severity,
                        event_count: count,
                        first_event: rule_state
                            .occurrences
                            .first()
                            .copied()
                            .unwrap_or_else(Utc::now),
                        last_event: event.timestamp,
                        sample_event_ids: rule_state.sample_ids.clone(),
                        generated_at: Utc::now(),
                    };

                    debug!(
                        "Alert triggered: rule='{}' count={} threshold={}",
                        compiled.rule.name, count, compiled.rule.threshold
                    );

                    rule_state.last_alert = Some(Utc::now());
                    rule_state.sample_ids.clear();
                    triggered.push(alert);
                }
            }
        }

        // Store alerts
        if !triggered.is_empty() {
            let mut alerts = self.alerts.write().await;
            alerts.extend(triggered.clone());
            // Keep last 1000 alerts
            if alerts.len() > 1000 {
                let drain_count = alerts.len() - 1000;
                alerts.drain(..drain_count);
            }
        }

        triggered
    }

    /// Process a batch of events.
    pub async fn process_events(&self, events: &[SiemEvent]) -> Vec<CorrelationAlert> {
        let mut all_alerts = Vec::new();
        for event in events {
            let alerts = self.process_event(event).await;
            all_alerts.extend(alerts);
        }
        all_alerts
    }

    /// Convert a correlation alert to a SIEM event for forwarding.
    pub fn alert_to_event(&self, alert: &CorrelationAlert, hostname: &str) -> SiemEvent {
        SiemEvent {
            timestamp: alert.generated_at,
            severity: alert.severity,
            category: EventCategory::Security,
            name: format!("correlation_alert_{}", alert.rule_id),
            description: alert.description.clone(),
            source_host: hostname.to_string(),
            source_ip: None,
            destination_ip: None,
            destination_port: None,
            user: None,
            process_name: None,
            process_id: None,
            file_path: None,
            custom_fields: serde_json::json!({
                "rule_id": alert.rule_id,
                "rule_name": alert.rule_name,
                "event_count": alert.event_count,
                "first_event": alert.first_event.to_rfc3339(),
                "last_event": alert.last_event.to_rfc3339(),
                "sample_event_ids": alert.sample_event_ids,
            }),
            event_id: uuid::Uuid::new_v4().to_string(),
            agent_version: agent_common::constants::AGENT_VERSION.to_string(),
        }
    }

    /// Get recent alerts.
    pub async fn recent_alerts(&self, limit: usize) -> Vec<CorrelationAlert> {
        let alerts = self.alerts.read().await;
        alerts.iter().rev().take(limit).cloned().collect()
    }

    /// Get the number of active rules.
    pub fn rule_count(&self) -> usize {
        self.rules.len()
    }

    /// Check if an event matches a compiled rule.
    fn event_matches(&self, event: &SiemEvent, compiled: &CompiledRule) -> bool {
        // Check severity
        if event.severity < compiled.rule.min_severity {
            return false;
        }

        // Check category filter
        if !compiled.rule.categories.is_empty()
            && !compiled.rule.categories.contains(&event.category)
        {
            return false;
        }

        // Check pattern against description and name
        compiled.compiled_pattern.is_match(&event.description)
            || compiled.compiled_pattern.is_match(&event.name)
    }
}

/// Built-in default correlation rules.
fn default_rules() -> Vec<CorrelationRule> {
    vec![
        CorrelationRule {
            id: "brute_force".to_string(),
            name: "Brute Force Detection".to_string(),
            description: "Multiple authentication failures detected".to_string(),
            categories: vec![EventCategory::Authentication],
            pattern: r"(?i)(fail|denied|invalid|unauthorized|rejected)".to_string(),
            min_severity: 3,
            threshold: 5,
            window_secs: 300, // 5 minutes
            alert_severity: 8,
            enabled: true,
        },
        CorrelationRule {
            id: "file_integrity_burst".to_string(),
            name: "Mass File Modification".to_string(),
            description: "Large number of file modifications detected".to_string(),
            categories: vec![EventCategory::FileIntegrity],
            pattern: r"(?i)(modified|changed|deleted|created)".to_string(),
            min_severity: 4,
            threshold: 50,
            window_secs: 60,
            alert_severity: 9,
            enabled: true,
        },
        CorrelationRule {
            id: "network_scan".to_string(),
            name: "Port Scan Detection".to_string(),
            description: "Possible port scan activity detected".to_string(),
            categories: vec![EventCategory::Network],
            pattern: r"(?i)(scan|probe|connection refused|reset)".to_string(),
            min_severity: 3,
            threshold: 20,
            window_secs: 60,
            alert_severity: 7,
            enabled: true,
        },
        CorrelationRule {
            id: "critical_errors".to_string(),
            name: "Critical Error Burst".to_string(),
            description: "Multiple critical errors in short period".to_string(),
            categories: vec![],
            pattern: r"(?i)(critical|emergency|panic|fatal)".to_string(),
            min_severity: 7,
            threshold: 3,
            window_secs: 300,
            alert_severity: 9,
            enabled: true,
        },
        CorrelationRule {
            id: "privilege_escalation".to_string(),
            name: "Privilege Escalation Attempt".to_string(),
            description: "Suspected privilege escalation activity".to_string(),
            categories: vec![EventCategory::Authentication, EventCategory::Security],
            pattern: r"(?i)(sudo|su |root|admin|privilege|escalat|setuid)".to_string(),
            min_severity: 5,
            threshold: 3,
            window_secs: 600,
            alert_severity: 9,
            enabled: true,
        },
        // ── Windows Event ID correlation rules ──
        CorrelationRule {
            id: "windows_logon_failure_burst".to_string(),
            name: "Windows Logon Failure Burst".to_string(),
            description: "Multiple Windows logon failures (Event ID 4625) — possible brute force"
                .to_string(),
            categories: vec![EventCategory::Authentication],
            pattern: r"EventID=4625".to_string(),
            min_severity: 0,
            threshold: 5,
            window_secs: 300, // 5 failures in 5 minutes
            alert_severity: 8,
            enabled: true,
        },
        CorrelationRule {
            id: "windows_account_changes".to_string(),
            name: "Rapid Account Changes".to_string(),
            description:
                "Multiple user account modifications in short time — possible compromise"
                    .to_string(),
            categories: vec![EventCategory::Authentication, EventCategory::Security],
            pattern: r"EventID=(4720|4722|4725|4726|4728|4732|4756)".to_string(),
            min_severity: 0,
            threshold: 3,
            window_secs: 300,
            alert_severity: 9,
            enabled: true,
        },
        CorrelationRule {
            id: "windows_service_install_burst".to_string(),
            name: "Multiple Services Installed".to_string(),
            description:
                "Multiple new services installed (Event ID 7045) — possible malware persistence"
                    .to_string(),
            categories: vec![EventCategory::System],
            pattern: r"EventID=7045".to_string(),
            min_severity: 0,
            threshold: 3,
            window_secs: 600, // 3 services in 10 minutes
            alert_severity: 8,
            enabled: true,
        },
        CorrelationRule {
            id: "windows_audit_log_cleared".to_string(),
            name: "Audit Log Cleared".to_string(),
            description: "Windows audit log was cleared (Event ID 1102) — anti-forensics indicator"
                .to_string(),
            categories: vec![EventCategory::Security, EventCategory::System],
            pattern: r"EventID=1102".to_string(),
            min_severity: 0,
            threshold: 1,   // Single event is critical
            window_secs: 60,
            alert_severity: 10,
            enabled: true,
        },
        CorrelationRule {
            id: "windows_firewall_changes".to_string(),
            name: "Firewall Configuration Changes".to_string(),
            description:
                "Multiple firewall rule changes — possible lateral movement preparation"
                    .to_string(),
            categories: vec![EventCategory::Network, EventCategory::Security],
            pattern: r"EventID=(2003|2004|2005|2006)".to_string(),
            min_severity: 0,
            threshold: 5,
            window_secs: 300,
            alert_severity: 7,
            enabled: true,
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use agent_common::constants::AGENT_VERSION;

    fn make_event(category: EventCategory, severity: u8, description: &str) -> SiemEvent {
        SiemEvent {
            timestamp: Utc::now(),
            severity,
            category,
            name: "test_event".to_string(),
            description: description.to_string(),
            source_host: "test-host".to_string(),
            source_ip: None,
            destination_ip: None,
            destination_port: None,
            user: None,
            process_name: None,
            process_id: None,
            file_path: None,
            custom_fields: serde_json::json!({}),
            event_id: uuid::Uuid::new_v4().to_string(),
            agent_version: AGENT_VERSION.to_string(),
        }
    }

    #[tokio::test]
    async fn test_correlation_engine_no_match() {
        let engine = CorrelationEngine::with_default_rules();
        let event = make_event(EventCategory::System, 2, "routine check passed");
        let alerts = engine.process_event(&event).await;
        assert!(alerts.is_empty());
    }

    #[tokio::test]
    async fn test_brute_force_detection() {
        // Use only the brute_force rule to avoid interference from other rules
        let rules = vec![CorrelationRule {
            id: "brute_force".to_string(),
            name: "Brute Force Detection".to_string(),
            description: "Multiple authentication failures detected".to_string(),
            categories: vec![EventCategory::Authentication],
            pattern: r"(?i)(fail|denied)".to_string(),
            min_severity: 3,
            threshold: 5,
            window_secs: 300,
            alert_severity: 8,
            enabled: true,
        }];
        let engine = CorrelationEngine::new(rules);

        // Simulate 5 failed login events (threshold for brute_force rule)
        for i in 0..5 {
            let event = make_event(
                EventCategory::Authentication,
                5,
                &format!("authentication failed for user test (attempt {})", i + 1),
            );
            let alerts = engine.process_event(&event).await;
            if i < 4 {
                assert!(alerts.is_empty(), "Should not alert before threshold");
            } else {
                assert_eq!(alerts.len(), 1, "Should alert at threshold");
                assert_eq!(alerts[0].rule_id, "brute_force");
                assert_eq!(alerts[0].event_count, 5);
            }
        }
    }

    #[tokio::test]
    async fn test_severity_filter() {
        let engine = CorrelationEngine::with_default_rules();

        // Low severity auth failure should not match brute_force (min_severity=3)
        for _ in 0..10 {
            let event = make_event(EventCategory::Authentication, 1, "login failed");
            let alerts = engine.process_event(&event).await;
            assert!(alerts.is_empty());
        }
    }

    #[tokio::test]
    async fn test_alert_to_event() {
        let engine = CorrelationEngine::with_default_rules();
        let alert = CorrelationAlert {
            rule_id: "test_rule".to_string(),
            rule_name: "Test Rule".to_string(),
            description: "Test alert".to_string(),
            severity: 8,
            event_count: 5,
            first_event: Utc::now(),
            last_event: Utc::now(),
            sample_event_ids: vec!["evt-1".to_string()],
            generated_at: Utc::now(),
        };

        let event = engine.alert_to_event(&alert, "test-host");
        assert_eq!(event.severity, 8);
        assert_eq!(event.category, EventCategory::Security);
        assert!(event.name.contains("test_rule"));
    }

    #[test]
    fn test_default_rules() {
        let rules = default_rules();
        assert!(!rules.is_empty());
        // Verify all patterns compile
        for rule in &rules {
            assert!(Regex::new(&rule.pattern).is_ok(), "Rule '{}' has invalid regex", rule.id);
        }
    }

    #[test]
    fn test_rule_count() {
        let engine = CorrelationEngine::with_default_rules();
        assert!(engine.rule_count() > 0);
    }
}
