// Copyright (c) 2024-2026 Cyber Threat Consulting
// SPDX-License-Identifier: MIT

//! Integration tests for agent-scanner.
//!
//! These tests exercise the public API surface of the three main components:
//!
//! - `CheckRunner` — parallel execution, timeouts, proof generation
//! - `ScoreCalculator` — weighted compliance scoring, valid 0-100 range
//! - `ProofGenerator` — SHA-256 proof hashes, tamper detection, signing
//!
//! No external services or encrypted storage are required; checks are
//! implemented inline as test doubles.

use agent_scanner::{
    check::{Check, CheckDefinitionBuilder, CheckOutput, CheckRegistry},
    error::ScannerResult,
    proof::{ProofGenerator, compute_sha256, verify_sha256},
    runner::{CheckRunner, RunnerConfig, ScanSummary},
    score::{CheckScoreInput, ScoreCalculator, ScoringConfig},
};
use agent_common::types::{CheckCategory, CheckResult, CheckSeverity, CheckStatus};
use async_trait::async_trait;
use std::sync::Arc;
use std::time::Duration;

// ─── Test-double checks ───────────────────────────────────────────────────────

struct PassCheck {
    def: agent_common::types::CheckDefinition,
}

#[async_trait]
impl Check for PassCheck {
    fn definition(&self) -> &agent_common::types::CheckDefinition {
        &self.def
    }
    async fn execute(&self) -> ScannerResult<CheckOutput> {
        Ok(CheckOutput::pass(
            "All good",
            serde_json::json!({"status": "ok"}),
        ))
    }
}

struct FailCheck {
    def: agent_common::types::CheckDefinition,
}

#[async_trait]
impl Check for FailCheck {
    fn definition(&self) -> &agent_common::types::CheckDefinition {
        &self.def
    }
    async fn execute(&self) -> ScannerResult<CheckOutput> {
        Ok(CheckOutput::fail(
            "Non-compliant",
            serde_json::json!({"reason": "policy violation"}),
        ))
    }
}

struct SlowCheck {
    def: agent_common::types::CheckDefinition,
    delay_ms: u64,
}

#[async_trait]
impl Check for SlowCheck {
    fn definition(&self) -> &agent_common::types::CheckDefinition {
        &self.def
    }
    async fn execute(&self) -> ScannerResult<CheckOutput> {
        tokio::time::sleep(Duration::from_millis(self.delay_ms)).await;
        Ok(CheckOutput::pass("Slow pass", serde_json::json!({})))
    }
}

// ─── Builder helpers ──────────────────────────────────────────────────────────

fn pass_check(id: &str) -> Arc<dyn Check> {
    Arc::new(PassCheck {
        def: CheckDefinitionBuilder::new(id)
            .name(format!("Pass Check {}", id))
            .category(CheckCategory::General)
            .build(),
    })
}

fn fail_check(id: &str) -> Arc<dyn Check> {
    Arc::new(FailCheck {
        def: CheckDefinitionBuilder::new(id)
            .name(format!("Fail Check {}", id))
            .category(CheckCategory::General)
            .build(),
    })
}

fn slow_check(id: &str, delay_ms: u64) -> Arc<dyn Check> {
    Arc::new(SlowCheck {
        def: CheckDefinitionBuilder::new(id)
            .name(format!("Slow Check {}", id))
            .build(),
        delay_ms,
    })
}

fn score_input(
    status: CheckStatus,
    severity: CheckSeverity,
    category: &str,
    frameworks: &[&str],
) -> CheckScoreInput {
    let result = match status {
        CheckStatus::Pass => CheckResult::pass("test"),
        CheckStatus::Fail => CheckResult::fail("test", "failed"),
        CheckStatus::Error => CheckResult::error("test", "error"),
        _ => CheckResult::pass("test"),
    };

    CheckScoreInput {
        result,
        severity,
        category: category.to_string(),
        frameworks: frameworks.iter().map(|s| s.to_string()).collect(),
    }
}

// ─── CheckRunner: parallel execution ─────────────────────────────────────────

/// Running 0 checks produces 0 results (edge case).
#[tokio::test]
async fn test_runner_with_zero_checks_returns_empty() {
    let registry = CheckRegistry::new();
    let runner = CheckRunner::with_defaults(Arc::new(registry));

    let results = runner.run_all().await;
    assert!(results.is_empty(), "No checks registered → no results");
}

/// A single passing check completes successfully with a valid proof.
#[tokio::test]
async fn test_runner_single_passing_check_produces_proof() {
    let mut registry = CheckRegistry::new();
    registry.register(pass_check("fw_check"));

    let runner = CheckRunner::with_defaults(Arc::new(registry));
    let exec = runner.run_check("fw_check").await.expect("run_check should succeed");

    assert_eq!(exec.result.status, CheckStatus::Pass);
    assert!(exec.proof.is_some(), "Proof must be generated by default");

    let proof = exec.proof.unwrap();
    assert_eq!(proof.data_hash.len(), 64, "Proof hash must be 64 hex chars");
    assert_eq!(proof.check_id, "fw_check");
    assert!(!proof.synced, "Proof should not be pre-synced");
}

/// A failing check returns `Fail` status and no proof hash mismatch.
#[tokio::test]
async fn test_runner_failing_check_returns_fail_status() {
    let mut registry = CheckRegistry::new();
    registry.register(fail_check("av_check"));

    let runner = CheckRunner::with_defaults(Arc::new(registry));
    let exec = runner.run_check("av_check").await.expect("run_check should succeed");

    assert_eq!(exec.result.status, CheckStatus::Fail);
}

/// Requesting a non-existent check ID returns `CheckNotFound`.
#[tokio::test]
async fn test_runner_nonexistent_check_returns_check_not_found_error() {
    use agent_scanner::error::ScannerError;

    let registry = CheckRegistry::new();
    let runner = CheckRunner::with_defaults(Arc::new(registry));

    let result = runner.run_check("does_not_exist").await;
    assert!(result.is_err());
    assert!(
        matches!(result.unwrap_err(), ScannerError::CheckNotFound(_)),
        "Error must be CheckNotFound"
    );
}

/// `run_all` executes multiple checks in parallel and returns all results.
#[tokio::test]
async fn test_runner_executes_multiple_checks_in_parallel() {
    let mut registry = CheckRegistry::new();
    for i in 0..8 {
        registry.register(pass_check(&format!("check_{}", i)));
    }
    registry.register(fail_check("check_fail"));

    let config = RunnerConfig {
        check_timeout_ms: 5_000,
        concurrency: 4,
        generate_proofs: true,
    };

    let runner = CheckRunner::new(Arc::new(registry), config);
    let results = runner.run_all().await;

    assert_eq!(results.len(), 9, "All 9 checks should produce results");

    let pass_count = results
        .iter()
        .filter(|r| r.result.status == CheckStatus::Pass)
        .count();
    let fail_count = results
        .iter()
        .filter(|r| r.result.status == CheckStatus::Fail)
        .count();

    assert_eq!(pass_count, 8, "8 passing checks expected");
    assert_eq!(fail_count, 1, "1 failing check expected");
}

/// A check that exceeds its timeout is reported as `Error` (timed out).
#[tokio::test]
async fn test_runner_check_timeout_returns_error_status() {
    let mut registry = CheckRegistry::new();
    registry.register(slow_check("lazy_check", 5_000)); // 5 second delay

    let config = RunnerConfig {
        check_timeout_ms: 50, // 50 ms timeout
        concurrency: 1,
        generate_proofs: false,
    };

    let runner = CheckRunner::new(Arc::new(registry), config);
    let exec = runner
        .run_check("lazy_check")
        .await
        .expect("run_check should not return Err even on timeout");

    assert_eq!(
        exec.result.status,
        CheckStatus::Error,
        "Timed-out check should produce Error status"
    );

    let msg = exec.result.message.as_deref().unwrap_or("");
    assert!(
        msg.contains("timed out"),
        "Error message should mention timeout, got: '{}'",
        msg
    );
}

/// Proof generation can be disabled; no proof is returned in that case.
#[tokio::test]
async fn test_runner_proof_generation_disabled_returns_none() {
    let mut registry = CheckRegistry::new();
    registry.register(pass_check("enc_check"));

    let config = RunnerConfig {
        check_timeout_ms: 5_000,
        concurrency: 1,
        generate_proofs: false,
    };

    let runner = CheckRunner::new(Arc::new(registry), config);
    let exec = runner.run_check("enc_check").await.unwrap();

    assert!(
        exec.proof.is_none(),
        "Proof should be None when generate_proofs is disabled"
    );
}

/// `run_filtered` with a framework list only executes matching checks.
#[tokio::test]
async fn test_runner_run_filtered_only_runs_framework_checks() {
    let mut registry = CheckRegistry::new();

    // NIS2 check
    registry.register(Arc::new(PassCheck {
        def: CheckDefinitionBuilder::new("nis2_check")
            .name("NIS2 Check")
            .category(CheckCategory::General)
            .framework("NIS2")
            .build(),
    }));

    // DORA check (not in active frameworks)
    registry.register(Arc::new(PassCheck {
        def: CheckDefinitionBuilder::new("dora_check")
            .name("DORA Check")
            .category(CheckCategory::General)
            .framework("DORA")
            .build(),
    }));

    let runner = CheckRunner::with_defaults(Arc::new(registry));
    let active = vec!["NIS2".to_string()];
    let results = runner.run_filtered(Some(&active)).await;

    assert_eq!(
        results.len(),
        1,
        "Only the NIS2 check should run, not the DORA check"
    );
    assert_eq!(results[0].result.check_id, "nis2_check");
}

// ─── ScanSummary ──────────────────────────────────────────────────────────────

/// `ScanSummary::from_results` correctly counts all status categories.
#[test]
fn test_scan_summary_counts_all_status_categories() {
    use agent_scanner::runner::CheckExecutionResult;

    let results = vec![
        CheckExecutionResult {
            result: CheckResult::pass("c1"),
            proof: None,
            duration_ms: 10,
        },
        CheckExecutionResult {
            result: CheckResult::pass("c2"),
            proof: None,
            duration_ms: 15,
        },
        CheckExecutionResult {
            result: CheckResult::fail("c3", "bad"),
            proof: None,
            duration_ms: 20,
        },
        CheckExecutionResult {
            result: CheckResult::error("c4", "boom"),
            proof: None,
            duration_ms: 5,
        },
    ];

    let summary = ScanSummary::from_results(&results, 50);

    assert_eq!(summary.total_checks, 4);
    assert_eq!(summary.passed, 2);
    assert_eq!(summary.failed, 1);
    assert_eq!(summary.errors, 1);
    assert_eq!(summary.skipped, 0);
    assert_eq!(summary.duration_ms, 50);

    // Score = 2 pass / (2 pass + 1 fail) countable = 66.67%
    assert!(
        (summary.score - 66.67).abs() < 0.1,
        "Score should be ~66.67, got {}",
        summary.score
    );
}

/// Score must be 100 when all checks pass.
#[test]
fn test_scan_summary_score_is_100_when_all_pass() {
    use agent_scanner::runner::CheckExecutionResult;

    let results: Vec<_> = (0..5)
        .map(|i| CheckExecutionResult {
            result: CheckResult::pass(&format!("c{}", i)),
            proof: None,
            duration_ms: 10,
        })
        .collect();

    let summary = ScanSummary::from_results(&results, 50);
    assert!(
        (summary.score - 100.0).abs() < 0.01,
        "Score must be 100 when all checks pass"
    );
}

/// Score must be 0 when all checks fail.
#[test]
fn test_scan_summary_score_is_0_when_all_fail() {
    use agent_scanner::runner::CheckExecutionResult;

    let results: Vec<_> = (0..3)
        .map(|i| CheckExecutionResult {
            result: CheckResult::fail(&format!("c{}", i), "failed"),
            proof: None,
            duration_ms: 10,
        })
        .collect();

    let summary = ScanSummary::from_results(&results, 30);
    assert!(
        summary.score < 0.01,
        "Score must be 0 when all checks fail"
    );
}

// ─── ScoreCalculator: 0-100 range guarantee ───────────────────────────────────

/// Score is always within [0.0, 100.0] regardless of input composition.
#[test]
fn test_score_always_in_0_100_range_for_arbitrary_inputs() {
    let calculator = ScoreCalculator::new();

    let test_cases: &[&[CheckScoreInput]] = &[
        &[],
        &[score_input(CheckStatus::Pass, CheckSeverity::Critical, "enc", &["NIS2"])],
        &[score_input(CheckStatus::Fail, CheckSeverity::Critical, "enc", &["NIS2"])],
        &[
            score_input(CheckStatus::Pass, CheckSeverity::High, "fw", &["NIS2"]),
            score_input(CheckStatus::Fail, CheckSeverity::Low, "av", &["DORA"]),
            score_input(CheckStatus::Error, CheckSeverity::Medium, "patch", &[]),
        ],
        &[
            score_input(CheckStatus::Pass, CheckSeverity::Info, "log", &[]),
            score_input(CheckStatus::Pass, CheckSeverity::Info, "log2", &[]),
        ],
    ];

    for inputs in test_cases {
        let result = calculator.calculate(inputs);
        assert!(
            result.score >= 0.0 && result.score <= 100.0,
            "Score {} is outside [0, 100] for {} inputs",
            result.score,
            inputs.len()
        );
    }
}

/// All checks passing → score 100.
#[test]
fn test_score_is_100_when_all_pass() {
    let calculator = ScoreCalculator::new();
    let inputs = vec![
        score_input(CheckStatus::Pass, CheckSeverity::Critical, "enc", &["NIS2"]),
        score_input(CheckStatus::Pass, CheckSeverity::High, "fw", &["DORA"]),
        score_input(CheckStatus::Pass, CheckSeverity::Medium, "av", &[]),
    ];

    let result = calculator.calculate(&inputs);
    assert!(
        (result.score - 100.0).abs() < 0.01,
        "All-pass score should be 100"
    );
    assert_eq!(result.passed_count, 3);
    assert_eq!(result.failed_count, 0);
}

/// All checks failing → score 0.
#[test]
fn test_score_is_0_when_all_fail() {
    let calculator = ScoreCalculator::new();
    let inputs = vec![
        score_input(CheckStatus::Fail, CheckSeverity::High, "enc", &[]),
        score_input(CheckStatus::Fail, CheckSeverity::High, "fw", &[]),
    ];

    let result = calculator.calculate(&inputs);
    assert!(
        result.score < 0.01,
        "All-fail score should be 0, got {}",
        result.score
    );
}

/// Empty input → score 0, all counts 0.
#[test]
fn test_score_empty_input_returns_zero() {
    let calculator = ScoreCalculator::new();
    let result = calculator.calculate(&[]);

    assert_eq!(result.score, 0.0);
    assert_eq!(result.total_count, 0);
    assert_eq!(result.passed_count, 0);
    assert_eq!(result.failed_count, 0);
}

/// Weighted scoring: a critical failure dominates a low-severity pass.
#[test]
fn test_weighted_scoring_critical_failure_dominates_low_pass() {
    let calculator = ScoreCalculator::new();
    let inputs = vec![
        // Critical fail: weight 4.0
        score_input(CheckStatus::Fail, CheckSeverity::Critical, "enc", &[]),
        // Low pass: weight 1.0
        score_input(CheckStatus::Pass, CheckSeverity::Low, "log", &[]),
    ];

    let result = calculator.calculate(&inputs);
    // Score = 1.0 / (4.0 + 1.0) * 100 = 20.0
    assert!(
        (result.score - 20.0).abs() < 0.01,
        "Score should be 20.0 for critical fail + low pass, got {}",
        result.score
    );
}

/// Category scores are computed and stored correctly.
#[test]
fn test_category_scores_are_computed() {
    let calculator = ScoreCalculator::new();
    let inputs = vec![
        score_input(CheckStatus::Pass, CheckSeverity::High, "encryption", &[]),
        score_input(CheckStatus::Pass, CheckSeverity::High, "encryption", &[]),
        score_input(CheckStatus::Fail, CheckSeverity::High, "firewall", &[]),
    ];

    let result = calculator.calculate(&inputs);

    assert!(result.category_scores.contains_key("encryption"));
    assert!(result.category_scores.contains_key("firewall"));

    let enc = &result.category_scores["encryption"];
    assert!((enc.score - 100.0).abs() < 0.01, "Encryption score should be 100");
    assert_eq!(enc.passed, 2);

    let fw = &result.category_scores["firewall"];
    assert!(fw.score < 0.01, "Firewall score should be 0");
    assert_eq!(fw.failed, 1);
}

/// Framework scores are computed per framework.
#[test]
fn test_framework_scores_are_computed() {
    let calculator = ScoreCalculator::new();
    let inputs = vec![
        score_input(
            CheckStatus::Pass,
            CheckSeverity::High,
            "enc",
            &["NIS2", "DORA"],
        ),
        score_input(CheckStatus::Fail, CheckSeverity::High, "fw", &["NIS2"]),
    ];

    let result = calculator.calculate(&inputs);

    assert!(result.framework_scores.contains_key("NIS2"));
    assert!(result.framework_scores.contains_key("DORA"));

    // NIS2: 1 pass (3.0) / 2 total (6.0) = 50%
    assert!(
        (result.framework_scores["NIS2"] - 50.0).abs() < 0.01,
        "NIS2 score should be 50%"
    );
    // DORA: 1 pass (3.0) / 1 total (3.0) = 100%
    assert!(
        (result.framework_scores["DORA"] - 100.0).abs() < 0.01,
        "DORA score should be 100%"
    );
}

/// Score delta is correctly computed from previous score.
#[test]
fn test_score_delta_from_previous_score() {
    let calculator = ScoreCalculator::new();
    let inputs = vec![
        score_input(CheckStatus::Pass, CheckSeverity::High, "enc", &[]),
        score_input(CheckStatus::Fail, CheckSeverity::High, "fw", &[]),
    ];

    let result = calculator.calculate_with_previous(&inputs, Some(30.0));

    assert!(result.delta.is_some(), "Delta should be present");
    // Score = 50%, previous = 30%, delta = +20
    assert!(
        (result.delta.unwrap() - 20.0).abs() < 0.01,
        "Delta should be +20.0"
    );
    assert_eq!(result.previous_score, Some(30.0));
}

/// `calculate_simple` produces correct unweighted score ignoring errors.
#[test]
fn test_simple_score_excludes_errors() {
    let calculator = ScoreCalculator::new();
    let results = vec![
        CheckResult::pass("c1"),
        CheckResult::pass("c2"),
        CheckResult::fail("c3", "bad"),
        CheckResult::error("c4", "boom"), // excluded from simple score
    ];

    let score = calculator.calculate_simple(&results);
    // 2 pass / (2 pass + 1 fail) = 66.67%
    assert!(
        (score - 66.67).abs() < 0.01,
        "Simple score should be ~66.67, got {}",
        score
    );
}

/// Custom `ScoringConfig` weights are respected.
#[test]
fn test_custom_scoring_config_weights_are_used() {
    // Make all weights equal — scoring becomes a plain percentage
    let config = ScoringConfig {
        weight_critical: 1.0,
        weight_high: 1.0,
        weight_medium: 1.0,
        weight_low: 1.0,
        weight_info: 1.0,
    };
    let calculator = ScoreCalculator::with_config(config);

    let inputs = vec![
        score_input(CheckStatus::Pass, CheckSeverity::Critical, "c", &[]),
        score_input(CheckStatus::Fail, CheckSeverity::Low, "c", &[]),
    ];

    let result = calculator.calculate(&inputs);
    // With equal weights: 1 pass / 2 total = 50%
    assert!(
        (result.score - 50.0).abs() < 0.01,
        "Equal-weight score should be 50.0, got {}",
        result.score
    );
}

// ─── ProofGenerator: SHA-256 hash properties ──────────────────────────────────

/// `compute_sha256` is deterministic and produces exactly 64 hex characters.
#[test]
fn test_compute_sha256_is_deterministic_and_correct_length() {
    let h1 = compute_sha256("sentinel compliance data");
    let h2 = compute_sha256("sentinel compliance data");

    assert_eq!(h1, h2, "SHA-256 must be deterministic");
    assert_eq!(h1.len(), 64, "SHA-256 hex output must be 64 chars");
    // Must be lowercase hex (no '0x' prefix, no uppercase letters)
    assert!(h1.chars().all(|c| c.is_ascii_hexdigit()), "Must be hex");
    assert!(!h1.contains(':'), "Must not have a prefix separator");
}

/// `verify_sha256` returns true for matching data/hash and false for mismatches.
#[test]
fn test_verify_sha256_correct_and_incorrect() {
    let data = "test payload";
    let correct_hash = compute_sha256(data);

    assert!(
        verify_sha256(data, &correct_hash),
        "verify_sha256 must return true for matching pair"
    );
    assert!(
        !verify_sha256("different payload", &correct_hash),
        "verify_sha256 must return false for wrong data"
    );
    assert!(
        !verify_sha256(data, &"0".repeat(64)),
        "verify_sha256 must return false for wrong hash"
    );
}

/// Different inputs produce different SHA-256 hashes (collision resistance sanity).
#[test]
fn test_compute_sha256_different_inputs_differ() {
    let h1 = compute_sha256("alpha");
    let h2 = compute_sha256("beta");
    assert_ne!(h1, h2, "Different inputs must produce different hashes");
}

/// `ProofGenerator::generate` produces a proof with a valid 64-char hash that
/// passes its own integrity check.
#[test]
fn test_proof_generator_creates_valid_proof() {
    use uuid::Uuid;

    let generator = ProofGenerator::new();
    let def = CheckDefinitionBuilder::new("disk_enc")
        .name("Disk Encryption")
        .category(CheckCategory::Encryption)
        .framework("NIS2")
        .build();
    let output = CheckOutput::pass(
        "BitLocker enabled",
        serde_json::json!({"algorithm": "AES-256"}),
    );
    let result_id = Uuid::new_v4();

    let proof = generator.generate(result_id, "disk_enc", &output, &def);

    assert_eq!(proof.check_id, "disk_enc");
    assert_eq!(proof.check_result_id, result_id);
    assert_eq!(proof.data_hash.len(), 64, "Hash must be 64 hex chars");
    assert!(!proof.synced);
    assert!(
        proof.expires_at.is_some(),
        "Proof must have an expiry date"
    );

    // Generator's own verify must pass
    assert!(
        generator.verify(&proof),
        "Generator.verify must return true for a freshly generated proof"
    );
}

/// A tampered proof fails `generator.verify`.
#[test]
fn test_proof_generator_detects_tampered_data() {
    use uuid::Uuid;

    let generator = ProofGenerator::new();
    let def = CheckDefinitionBuilder::new("av_check")
        .name("Antivirus")
        .build();
    let output = CheckOutput::pass("AV active", serde_json::json!({}));

    let mut proof = generator.generate(Uuid::new_v4(), "av_check", &output, &def);

    // Tamper with the proof data
    proof.data = serde_json::json!({"tampered": true, "original": false});

    assert!(
        !generator.verify(&proof),
        "Tampered proof must fail generator.verify"
    );
}

/// Proof expiration date is approximately `retention_days` in the future.
#[test]
fn test_proof_generator_expiry_matches_retention() {
    use chrono::Utc;
    use uuid::Uuid;

    let retention_days = 30i64;
    let generator = ProofGenerator::with_retention(retention_days);
    let def = CheckDefinitionBuilder::new("exp_check").name("Expiry Check").build();
    let output = CheckOutput::pass("ok", serde_json::json!({}));

    let proof = generator.generate(Uuid::new_v4(), "exp_check", &output, &def);
    let expires = proof.expires_at.expect("Proof must have expiry");

    let days_until_expiry = (expires - Utc::now()).num_days();
    assert!(
        (retention_days - 1..=retention_days).contains(&days_until_expiry),
        "Proof should expire in ~{} days, got {}",
        retention_days,
        days_until_expiry
    );
}

/// HMAC-SHA256 signature can be applied and verified; wrong key fails.
#[test]
fn test_proof_generator_sign_and_verify_signature() {
    use uuid::Uuid;

    let generator = ProofGenerator::new();
    let def = CheckDefinitionBuilder::new("sig_check").name("Sig Check").build();
    let output = CheckOutput::pass("signed", serde_json::json!({}));

    let mut proof = generator.generate(Uuid::new_v4(), "sig_check", &output, &def);
    let key = b"super-secret-32-byte-signing-key";

    // Initially no signature
    assert!(proof.signature.is_none());

    generator.sign(&mut proof, key);
    assert!(
        proof.signature.is_some(),
        "Proof should have a signature after sign()"
    );
    assert!(
        proof
            .signature
            .as_ref()
            .unwrap()
            .starts_with("hmac-sha256:"),
        "Signature must use hmac-sha256 scheme"
    );

    // Correct key verifies
    assert!(
        generator.verify_signature(&proof, key),
        "Correct key must verify the signature"
    );

    // Wrong key does not verify
    assert!(
        !generator.verify_signature(&proof, b"wrong-key-entirely-different"),
        "Wrong key must not verify the signature"
    );
}

/// Proof with no signature returns false from `verify_signature`.
#[test]
fn test_proof_verify_signature_without_signature_returns_false() {
    use uuid::Uuid;

    let generator = ProofGenerator::new();
    let def = CheckDefinitionBuilder::new("nosig_check").name("NoSig").build();
    let output = CheckOutput::pass("no sig", serde_json::json!({}));
    let proof = generator.generate(Uuid::new_v4(), "nosig_check", &output, &def);

    assert!(
        !generator.verify_signature(&proof, b"any-key"),
        "Unsigned proof must return false from verify_signature"
    );
}
